Repository rs-station/reciprocalspaceship, pull requests merged in 2021-01, with the labels that each got.

#40 Add rs.read_csv() to construct DataSet from CSV file
  docs/api/index.rst
  reciprocalspaceship/__init__.py
  reciprocalspaceship/io/__init__.py
  reciprocalspaceship/io/csv.py
  tests/io/test_csv.py
Labels: API, enhancement

#45 Frenched wilson
  reciprocalspaceship/algorithms/scale_merged_intensities.py
  tests/algorithms/test_scale_merged_intensities.py
Labels: bug

#47 Add DataSet.centrics and DataSet.acentrics accessors
  reciprocalspaceship/dataset.py
  tests/test_dataset.py
Labels: enhancement
