Repository rs-station/reciprocalspaceship, pull requests merged in 2021-07, with the labels that each got.

#70 Add rs.read_pickle() helper method
  docs/api/index.rst
  reciprocalspaceship/__init__.py
  reciprocalspaceship/dataset.py
  reciprocalspaceship/io/__init__.py
  reciprocalspaceship/io/pickle.py
  tests/io/test_pickle.py
Labels: API, documentation

#71 Update reciprocalspaceship to support pandas 1.3.0
  reciprocalspaceship/dataset.py
  setup.py
  tests/algorithms/test_merge.py
  tests/algorithms/test_scale_merged_intensities.py
  tests/dtypes/conftest.py
  tests/dtypes/test_floats_pandas.py
  tests/dtypes/test_ints_pandas.py
  tests/utils/test_cell.py
Labels: version

#73 Compute the angular Ewald offset when loading streams
  reciprocalspaceship/dataset.py
  reciprocalspaceship/io/crystfel.py
Labels: enhancement

#74 add support for generators to rs.concat
  reciprocalspaceship/concat.py
Labels: bug

#75 added an angle_between function to rs.utils
  reciprocalspaceship/io/crystfel.py
  reciprocalspaceship/utils/__init__.py
  reciprocalspaceship/utils/math.py
  tests/utils/test_angle_between.py
Labels: enhancement
