Repository rs-station/reciprocalspaceship, pull requests merged in 2021-02, with the labels that each got.

#48 Chevychase
  reciprocalspaceship/algorithms/scale_merged_intensities.py
  tests/algorithms/conftest.py
  tests/algorithms/test_scale_merged_intensities.py
  tests/data/french_wilson/diagnostics.py
  tests/data/french_wilson/fw_mcmc_data.csv
  tests/data/french_wilson/fw_test_data.csv
  tests/data/french_wilson/gen_fw_reference_data.py
  tests/data/french_wilson/gen_mcmc_reference_data.py
Labels: enhancement

#51 Clean up rs.read_precognition()
  reciprocalspaceship/io/precognition.py
  tests/io/conftest.py
  tests/io/test_precognition.py
Labels: API

#50 Add crystfel streams to `rs/io` module
  reciprocalspaceship/__init__.py
  reciprocalspaceship/io/__init__.py
  reciprocalspaceship/io/crystfel.py
  tests/data/crystfel/crystfel.stream
  tests/io/test_crystfel.py
Labels: API, enhancement

#52 Add example notebooks' dependencies to dev install
  postBuild
  setup.py
Labels: documentation, enhancement
