Repository rs-station/reciprocalspaceship, pull requests merged in 2021-06, with the labels that each got.

#63 Fix sign of phase shift in DataSet.apply_symop
  reciprocalspaceship/dataset.py
  tests/test_dataset.py
  tests/test_dataset_grid.py
  tests/test_dataset_symops.py
Labels: bug

#66 Add documentation for rs.utils functions to Developers section
  docs/conf.py
  docs/developers/index.rst
  docs/developers/utilities.rst
  reciprocalspaceship/utils/__init__.py
  reciprocalspaceship/utils/rfree.py
  reciprocalspaceship/utils/structurefactors.py
  setup.py
Labels: documentation

#68 Fix behavior of rs.utils.generate_reciprocal_asu() with anomalous flag
  reciprocalspaceship/utils/asu.py
  tests/utils/test_asu.py
Labels: enhancement

#67 mostly vectorized phase restriction calculation
  reciprocalspaceship/utils/phases.py
Labels: enhancement
